# Generated by Django 6.0.2 on 2026-04-09 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('favorite_method', models.CharField(choices=[('espresso', 'Espresso'), ('filter', 'Filter'), ('french_press', 'French Press'), ('pour_over', 'Pour Over'), ('aeropress', 'AeroPress'), ('moka_pot', 'Moka Pot')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
